spring:
  datasource:
    postgres:
      url: ${DB_URL:jdbc:postgresql:local-moz-db}
      username: ${DB_USER:postgres}
      password: ${DB_PASS:postgres}
    hikari:
      maximum-pool-size: 4

  data:
    mongodb:
      uri: ${MONGODB_URL}
