server:
  port: 9001

#spring:
#  application:
#    name: calculation-service

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs/swagger-ui.html
    doc-expansion: none
  packages-to-scan:
    - com.mapofzones.calculations.controllers
